# warning: this script was generated by AI :D

import numpy as np
import trimesh
from trimesh.visual.material import PBRMaterial
from trimesh.visual.texture import TextureVisuals

rng = np.random.default_rng(42)

NUM_OBJECTS = 300
SCENE_SIZE = 20.0

scene = trimesh.Scene()


def random_mesh():
    """Generate a random-ish primitive or convex blob."""
    kind = rng.choice(["box", "sphere", "ico", "cylinder", "blob"])

    if kind == "box":
        return trimesh.creation.box(extents=rng.uniform(0.3, 1.8, size=3))

    if kind == "sphere":
        return trimesh.creation.uv_sphere(
            radius=rng.uniform(0.25, 0.9),
            count=[12, 12],
        )

    if kind == "ico":
        mesh = trimesh.creation.icosphere(
            subdivisions=1,
            radius=rng.uniform(0.3, 1.0),
        )
        mesh.vertices *= rng.uniform(0.6, 1.5, size=3)
        return mesh

    if kind == "cylinder":
        return trimesh.creation.cylinder(
            radius=rng.uniform(0.2, 0.7),
            height=rng.uniform(0.4, 1.8),
            sections=12,
        )

    # Random convex blob
    points = rng.normal(size=(20, 3))
    points *= rng.uniform(0.3, 1.0, size=3)
    return trimesh.convex.convex_hull(points)


for i in range(NUM_OBJECTS):
    mesh = random_mesh()

    # Transparent random PBR color
    rgba = [
        float(rng.uniform(0.1, 1.0)),
        float(rng.uniform(0.1, 1.0)),
        float(rng.uniform(0.1, 1.0)),
        float(rng.uniform(0.08, 0.5)),
    ]

    material = PBRMaterial(
        name=f"transparent_{i}",
        baseColorFactor=rgba,
        metallicFactor=0.0,
        roughnessFactor=0.5,
        alphaMode="BLEND",
        doubleSided=True,
    )

    mesh.visual = TextureVisuals(material=material)

    # Random transform
    transform = trimesh.transformations.compose_matrix(
        translate=rng.uniform(
            -SCENE_SIZE / 2,
            SCENE_SIZE / 2,
            size=3,
        ),
        angles=rng.uniform(0.0, np.pi * 2.0, size=3),
        scale=rng.uniform(0.7, 1.3, size=3),
    )

    scene.add_geometry(
        mesh,
        node_name=f"object_{i}",
        geom_name=f"mesh_{i}",
        transform=transform,
    )


# Add a few large overlapping transparent objects to make OIT
# artifacts especially obvious.
for i in range(15):
    mesh = trimesh.creation.icosphere(subdivisions=2, radius=2.5)

    material = PBRMaterial(
        name=f"big_transparent_{i}",
        baseColorFactor=[
            float(rng.random()),
            float(rng.random()),
            float(rng.random()),
            0.12,
        ],
        roughnessFactor=0.4,
        alphaMode="BLEND",
        doubleSided=True,
    )

    mesh.visual = TextureVisuals(material=material)

    transform = trimesh.transformations.translation_matrix(rng.uniform(-5, 5, size=3))

    scene.add_geometry(
        mesh,
        node_name=f"big_object_{i}",
        transform=transform,
    )


# Binary glTF
scene.export("oit_test.glb")

# Or JSON .gltf + external buffers:
# scene.export("oit_test.gltf")

print(f"Wrote oit_test.glb with {len(scene.geometry)} transparent objects")
