# warning: this script was generated by AI :D

import numpy as np
import trimesh
from trimesh.visual.material import PBRMaterial
from trimesh.visual.texture import TextureVisuals

rng = np.random.default_rng(42)

NUM_OBJECTS = 500
SCENE_SIZE = 50

scene = trimesh.Scene()


def random_mesh():
    kind = rng.choice(["box", "sphere", "ico", "cylinder", "blob"])

    if kind == "box":
        return trimesh.creation.box(extents=rng.uniform(0.3, 1.8, size=3))

    if kind == "sphere":
        return trimesh.creation.icosphere(
            radius=rng.uniform(0.25, 0.9),
            count=[12, 12],
            subdivisions=5,
        )

    if kind == "ico":
        mesh = trimesh.creation.icosphere(
            subdivisions=1,
            radius=rng.uniform(0.3, 1.0),
        )
        mesh.vertices *= rng.uniform(0.6, 1.5, size=3)
        return mesh

    if kind == "cylinder":
        return trimesh.creation.cylinder(
            radius=rng.uniform(0.2, 2.5),
            height=rng.uniform(0.4, 1.8),
            sections=20,
        )

    points = rng.normal(size=(20, 3))
    points *= rng.uniform(0.3, 1.0, size=3)
    return trimesh.convex.convex_hull(points)


for i in range(NUM_OBJECTS):
    mesh = random_mesh()

    rgba = [
        float(rng.uniform(0.1, 1.0)),
        float(rng.uniform(0.1, 1.0)),
        float(rng.uniform(0.1, 1.0)),
        float(rng.uniform(0.08, 0.8)),
    ]

    material = PBRMaterial(
        name=f"transparent_{i}",
        baseColorFactor=rgba,
        metallicFactor=0.0,
        roughnessFactor=0.5,
        alphaMode="BLEND",
        doubleSided=True,
    )

    mesh.visual = TextureVisuals(material=material)

    transform = trimesh.transformations.compose_matrix(
        translate=rng.uniform(
            -SCENE_SIZE / 2,
            SCENE_SIZE / 2,
            size=3,
        ),
        angles=rng.uniform(0.0, np.pi * 2.0, size=3),
        scale=rng.uniform(0.7, 1.3, size=3),
    )

    scene.add_geometry(
        mesh,
        node_name=f"object_{i}",
        geom_name=f"mesh_{i}",
        transform=transform,
    )


scene.export("shapes.glb")

print(f"Wrote oit_test.glb with {len(scene.geometry)} transparent objects")
